### ISSUE TITLE
White page when running in production

### ISSUE THREAD

**Issue by williamrussell-grindr** [moifort/generator-jhipster-bootstrap-material-design#14]
I have a generic Monolith application from JHipster. The first thing I did was install Material Design. 
However, when I run for production, it only displays a blank white page. 

Any help?

**Comment by moifort** [comment]
1. What's your JHipster console output display? In which profile did you run your application (dev, production, etc.)?
2. What's your Chrome/Firefox/Other console output display?

**Comment by williamrussell-grindr** [comment]
Thanks for your response Moifort.
It does appear to be my setup when compiling for production.

1. This does not display anything, just normal output. 

2. Safari Logs
`


Error #1
[Error] ReferenceError: Can't find variable: compileServiceConfig
	(anonymous function) (app-3b7028c2c3.js:4:1002)
	global code (app-3b7028c2c3.js:4:1014)

Error #2
[Error] Error: [$injector:modulerr] Failed to instantiate module acmeSiteApp due to:
[$injector:unpr] Unknown provider: ENV
http://errors.angularjs.org/1.5.2/$injector/unpr?p0=ENV
http://localhost:9000/app/vendor-69166b4283.js:3:22494
http://localhost:9000/app/vendor-69166b4283.js:4:11267
r@http://localhost:9000/app/vendor-69166b4283.js:4:10194
i@http://localhost:9000/app/vendor-69166b4283.js:4:10494
a@http://localhost:9000/app/vendor-69166b4283.js:4:10694
r@http://localhost:9000/app/vendor-69166b4283.js:4:9586
http://localhost:9000/app/vendor-69166b4283.js:4:9706
o@http://localhost:9000/app/vendor-69166b4283.js:3:22941
d@http://localhost:9000/app/vendor-69166b4283.js:4:9483
it@http://localhost:9000/app/vendor-69166b4283.js:4:11433
s@http://localhost:9000/app/vendor-69166b4283.js:3:30324
se@http://localhost:9000/app/vendor-69166b4283.js:3:30633
ae@http://localhost:9000/app/vendor-69166b4283.js:3:29881
http://localhost:9000/app/vendor-69166b4283.js:8:25485
u@http://localhost:9000/app/vendor-69166b4283.js:2:6585
fireWith@http://localhost:9000/app/vendor-69166b4283.js:2:7349
ready@http://localhost:9000/app/vendor-69166b4283.js:2:9176
a@http://localhost:9000/app/vendor-69166b4283.js:1:949
http://errors.angularjs.org/1.5.2/$injector/modulerr?p0=acmeSiteApp&p1=%5B%24injector%3Aunpr%5D%20Unknown%20provider%3A%20ENV%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.2%2F%24injector%2Funpr%3Fp0%3DENV%0Ahttp%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A3%3A22494%0Ahttp%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A4%3A11267%0Ar%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A4%3A10194%0Ai%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A4%3A10494%0Aa%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A4%3A10694%0Ar%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A4%3A9586%0Ahttp%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A4%3A9706%0Ao%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A3%3A22941%0Ad%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A4%3A9483%0Ait%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A4%3A11433%0As%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A3%3A30324%0Ase%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A3%3A30633%0Aae%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A3%3A29881%0Ahttp%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A8%3A25485%0Au%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A2%3A6585%0AfireWith%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A2%3A7349%0Aready%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A2%3A9176%0Aa%40http%3A%2F%2Flocalhost%3A9000%2Fapp%2Fvendor-69166b4283.js%3A1%3A949
	(anonymous function) (vendor-69166b4283.js:4:9997)
	o (vendor-69166b4283.js:3:22942)
	d (vendor-69166b4283.js:4:9484)
	it (vendor-69166b4283.js:4:11434)
	s (vendor-69166b4283.js:3:30325)
	se (vendor-69166b4283.js:3:30634)
	ae (vendor-69166b4283.js:3:29882)
	(anonymous function) (vendor-69166b4283.js:8:25486)
	u (vendor-69166b4283.js:2:6586)
	fireWith (vendor-69166b4283.js:2:7350)
	ready (vendor-69166b4283.js:2:9177)
	a (vendor-69166b4283.js:1:950)`

3. Attached youtube video showing an example (unlisted)
[Youtube Material Design Issue](https://youtu.be/NPG5lL_qte4)

**Comment by williamrussell-grindr** [comment]
bootstrap-material.config.js cannot find "compileServiceConfig"?

`(function() {
    'use strict';

    angular
        .module('acmeSiteApp')
        .config(bootstrapMaterialDesignConfig);

    compileServiceConfig.$inject = [];

    function bootstrapMaterialDesignConfig() {
        $.material.init();

    }
})();
`

**Comment by williamrussell-grindr** [comment]
Update:

Im not sure if this is correct, 
but I changed:
   compileServiceConfig.$inject = []; 
to 
  bootstrapMaterialDesignConfig.$inject = [];

And I get this error now.

Error: [$injector:modulerr] Failed to instantiate module acmeSiteApp due to:
undefined is not an object (evaluating '$.material.init')

**Comment by williamrussell-grindr** [comment]
bootstrapMaterialDesignConfig.$inject = [];

plus clearing the cache seems to have fixed it.

letting you close this... in-case that line was wrong.

**Comment by moifort** [comment]
Cool! 👍 Have a nice coding!
