### ISSUE TITLE
issue while running "yo jhipster-bootstrap-material-design"

### ISSUE THREAD

**Issue by saad14092** [moifort/generator-jhipster-bootstrap-material-design#23]
Hello,
I am using the latest version of JHipster with Angular 5 for the front end. Here is the stack trace, any ideas what might be the problem ? Thank you.

? Do you want to install Bootstrap Material design? (y/N) y
? Do you want to install Bootstrap Material design? Yes
Composing JHipster configuration with module bootstrap-material-design
WARNING! DEPRECATED! The JHipster module sub-generator is deprecated.
WARNING! Please import the generator-base.js using commonJS require or ES2015 import.
WARNING! See http://www.jhipster.tech/modules/creating-a-module for more details.

Reading the JHipster project configuration for your module

Unable to find bower.json. Reference to bower dependency (name: arrive, version:2.3.0) not added.

events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: this.debug is not a function
    at Object.addBowerDependency (E:\work\git\mmz\node_modules\generator-jhipster\generators\generator-base.js:608:18)
    at child.writing (C:\Users\SAAD\AppData\Local\Yarn\Data\global\node_modules\generator-jhipster-bootstrap-material-design\generators\app\index.js:66:22)
    at C:\Users\SAAD\AppData\Local\Yarn\Data\global\node_modules\yeoman-generator\lib\base.js:430:16
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by pascalgrimaud** [comment]
Simply because this module is deprecated and only works with AngularJS.

**Comment by volthier** [comment]
Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo jhipster-bootstrap-material-design


     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Welcome to the JHipster |
   `---------´   |    Bootstrap Material    |
    ( _´U`_ )    | design generator! v3.5.1 |
    /___A___\    '--------------------------'
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Do you want to install Bootstrap Material design? Yes
Error  

You don't seem to have a generator with the name “jhipster:modules” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-jhipster:modules.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators. 

If yo cannot find the generator, run yo doctor to troubleshoot your system.

**Comment by leantorres73** [comment]
I'm having the same issue with Java+React project.

**Comment by smlshn** [comment]
Facing with the same issue. Cannot install bootstrap-material-design with jhipster v5.2.1.

**Comment by pascalgrimaud** [comment]
@leantorres73 @smlshn :

> Simply because this module is deprecated and only works with AngularJS.

**Comment by sinrt** [comment]
I am also having the same issue in jhipster 5.28.0

**Comment by cchunduri** [comment]
I'm using Jhipster 6.3.0, I'm also getting the same issue.

**Comment by maherbel** [comment]
Any news on this issue ? having the same problem with Jhipster 6.6.0 (Java/React)

**Comment by moifort** [comment]
Hey @maherbel this generator is deprecated (since 4 years). I close the issue!
