### ISSUE TITLE
Add support for theming

### ISSUE THREAD

**Issue by shawmanz32na** [moifort/generator-jhipster-bootstrap-material-design#6]
I'm not looking for a complete color scheme selector, but it would be nice if there was support for changing the primary color from teal to, let's say, deep-purple.

It appears that the bootstrap theme that this package leverages allows this type of thing when using SASS, but there's no mention of how to leverage that feature when using this generator.

**Comment by moifort** [comment]
Yes he can be a good idea!

**Comment by moifort** [comment]
I close the issue, because I don't have the time to work on it. If you want you can make a PR!
